version: '3'
services:
  db:
    image: postgres:13.4-alpine
    environment:
      POSTGRES_PASSWORD: secret
      POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_DB: database_dev
    env_file:
      - .env

    ports:
      - "5432:5432"
    volumes:
      - ./database_data:/var/lib/postgresql/data
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql

  app:
    build: .
    volumes:
      - ".:/app/"
    depends_on:
      - db
    stdin_open: true
    tty: true
    env_file:
      - .env

  #admin:
  #  image: adminer
  #  depends_on: 
  #    - db
  #  ports:
  #    - 8282:8080